#!/bin/bash
__track_usage "$(basename "$0")"

# Temp dir with historic log file to easily traverse with _ptdir
# Used w/ corresponding zsh function tdir to actually do the directory switching in parent shell

TMP_FILE_TEMPLATE=""

if is_os_linux ; then
  TMP_FILE_TEMPLATE="nj.XXX"
elif is_os_osx ; then
  TMP_FILE_TEMPLATE="nj"
else
  print_error "Unknown operating system"
  exit 1
fi

log_file="$HOME/.tdir";
_date=$(date "+%Y_%m_%d__%H_%M_%S_%p");
_context=$(pwd)
_dir=$(mktemp -d -t "$TMP_FILE_TEMPLATE") \
  && echo -e "$_date\t$_dir\t$_context" >> "$log_file" \
  && echo "$_dir" \
  || { print_error "Failed to create temp dir, staying in cur dir."; echo "$PWD"; exit 1; } # echo PWD because the wrapper to this is `cd $(_ptdr)`
