#!/bin/bash

echo '<!DOCTYPE html>
    <html ⚡4email data-css-strict>
  
        <head>
            <meta name="robots" content="noindex, nofollow">
            <meta charset="utf-8">
            <script async src="https://cdn.ampproject.org/v0.js"></script>
        
            <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
            <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
            <script custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js" async></script>
            <script async custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js"></script>
            <style amp4email-boilerplate>body{visibility:hidden}</style>
        </head>
        <body>
            %SPELLBOUND_WIDGET_PLACEHOLDER%
        </body>
    </html>' | pbcopy