#!/bin/bash

recentBranches() {
  git reflog | grep 'moving from' | awk -F"moving from " '{print $2}' | head -n 20 | sed -e 's/ to /\'$'\n/g' | sort | uniq
}

echo "Checkout which branch?"
recentBranches | nl
read -p "? " n

switch_to=$(recentBranches | sed -n "$n"p)
echo "Switching to: $switch_to"
git checkout "$switch_to"