#!/bin/bash

# Ex usage:
#
# > map "geoiplookup" < ip_list
# > cat access.log | map "./process_log_line.sh"

fn="$1"

if [ -z "$fn" ]; then
  echo "map requires argument of function to map stdin against"
  exit 1
fi

which "$fn" >/dev/null || { echo "Argument is not a valid function."; exit 1; }

while read x; do
  "$fn" "$x"
done

