#!/bin/bash

# Moves most recently downloaded file to a new temp directory

FILENAME=$(ls -tr ~/Downloads | tail -n 1)
FILEPATH=$(expandPath "~/Downloads/$FILENAME")

ARG="$1"
# Was path provided? If so move file to that location
if [ -n "$ARG" ]; then
  TDIR=$(realpath "$1")
  exitIfError "$?" "Argument provided not valid filepath" || exit 1

  [ -d "$TDIR" ]
  exitIfError "$?" "Argument provided not valid filepath" || exit 1

else
  TDIR=$(_tdir)
  exitIfError "$?" "Failed to create temp dir" || exit 1
fi

prompt_yes "Move $FILEPATH to $TDIR"

mv "$FILEPATH" "$TDIR/$FILENAME"
exitIfError "$?" "Failed to move file" || exit 1

echo "$TDIR"
