#!/bin/bash
# Run as: . npm_path to add the node_modules bin of the current directory to the PATH of the current shell

# TODO: Check path for duplicates before appending

NPM_BIN_PATH="$(pwd)/node_modules/.bin"

if [ -d "$NPM_BIN_PATH" ]; then
  export PATH="$PATH:$NPM_BIN_PATH"
else
  echo "No node_modules bin found in current directory, not appending to path"
  echo "Not found: $NPM_BIN_PATH"
  exit 1
fi
