#!/bin/bash
__track_usage "$(basename "$0")"

promptYes() {
  echo "$1"
  while true; do
      read -p "Type (y/n) :" yn
      case $yn in
          [Yy]* ) break;;
          [Nn]* ) exit 1;;
          * ) echo "Please answer yes or no.";;
      esac
  done
}

promptYes "$1"
