#!/bin/bash

promptYes() {
  while true; do
      read -p "$1 :" yn
      case $yn in
          [Yy]* ) break;;
          [Nn]* ) exit 1;;
          * ) echo "Please answer yes or no.";;
      esac
  done
}

branch=$(gcurb)

if [[ "$branch" == "dev" ]]; then
  promptYes "Confirm pushing to dev. [Y or N]"
elif [[ "$branch" == "master" ]]; then
  promptYes "Confirm pushing to master. [Y or N]"
else
  echo "Pushing to origin $branch..."
  sleep 0.5 # Small amount of time to cancel with ^C 
fi

resp=$(git push origin "$branch" 2>&1)
if [ "$?" != 0 ]; then
  echo "$resp"
  promptYes "Force push?"
  git push origin "$branch" --force-with-lease
else
  echo "$resp"
fi
