#!/bin/bash

promptYes() {
  while true; do
      read -p "$1 :" yn
      case $yn in
          [Yy]* ) break;;
          [Nn]* ) exit 1;;
          * ) echo "Please answer yes or no.";;
      esac
  done
}

branch=$(gcurb)

if [[ "$branch" == "dev" ]]; then
  promptYes "Confirm pushing to dev. [Y or N]"
elif [[ "$branch" == "master" ]]; then
  promptYes "Confirm pushing to master. [Y or N]"
else
  echo "Pushing to origin $branch in 2 seconds..."
  sleep 2
fi

git push origin "$branch"
