#!/bin/bash

_g_isClean
exitIfError "$?" "Cannot rebase, uncommited changes." || exit 1

if [ "$(_g)" == "dev" ]; then
  print_error "Cannot rebase dev onto dev"
  exit 1
fi

git rebase --committer-date-is-author-date dev
