#!/bin/bash
__track_usage "$(basename "$0")"

# TODO: Optional space delimted list as flag

# Uniqs a line delimited list while retaining the original order
#   Ex:
#     a
#     b
#     c
#     a
#     d
#     
#     ->
#     a
#     b
#     c
#     d

awk '!x[$0]++'
