#!/bin/bash
__track_usage "$(basename "$0")"

C_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
OPTS_PATH="$C_PATH/tcurl.opts"

curl -w "@""$OPTS_PATH/format-default.txt" -o /dev/null -s "$1"
